# Generated by Django 5.0.7 on 2024-07-19 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordereditem',
            name='items',
        ),
        migrations.AddField(
            model_name='ordereditem',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order_service.order'),
        ),
    ]
