# Generated by Django 5.0.7 on 2024-07-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_service', '0002_remove_ordereditem_items_ordereditem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditem',
            name='price_fetch_in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
