# Generated by Django 5.0.7 on 2024-07-19 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_service', '0003_ordereditem_price_fetch_in_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordereditem',
            name='price_fetch_in_progress',
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order_service.order'),
        ),
    ]
